version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: paint-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
    volumes:
      - paint_mongo_data:/var/lib/mongodb
      - ./mongo/mongod_log:/var/log/mongodb/
    command: mongod --logpath /var/log/mongodb/mongod.log --config /etc/mongod.conf --keyFile /var/lib/mongodb/mongodb-keyfile
    networks:
      pic_network:
        ipv4_address: 172.18.0.103 # IP кешируется в Docker после смены нужно сделать `docker network prune`

  paint-back-api:
    image: paint-back-api-img
    container_name: "paint-back-api"
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./backend-api/.env.$ENVIRONMENT
    environment:
      - NODE_ENV=$ENVIRONMENT
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./backend-api/Dockerfile
    volumes:
      - ./backend-api/logs:/app/logs
    networks:
      pic_network:
        ipv4_address: 172.18.0.102 # IP кешируется в Docker после смены нужно сделать `docker network prune`

  paint-front:
    image: paint-front-img
    container_name: "paint-front"
    restart: unless-stopped
    depends_on:
      - mongodb
      - paint-back-api
    env_file:
      - ./frontend/.env.$ENVIRONMENT
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      pic_network:
        ipv4_address: 172.18.0.101 # IP кешируется в Docker после смены нужно сделать `docker network prune`

  art-config:
    image: art-config-img
    container_name: "art-config"
    restart: unless-stopped
    depends_on:
      - mongodb
      - paint-back-api
    env_file:
      - ./artConfigurator/.env
    ports:
      - 8085:8085
    build:
      context: .
      dockerfile: ./artConfigurator/Dockerfile
    networks: # IP кешируется в Docker после смены нужно сделать `docker network prune`
      pic_network:
        ipv4_address: 172.18.0.100

#https://github.com/arunbandari/mongo-gui/tree/master

# mongo-gui:
#   container_name: "mongo-gui"
#   image: ugleiton/mongo-gui
#   restart: unless-stopped
#   env_file:
#     - .env
#   ports:
#     - "4321:4321"
#   environment:
#     - MONGO_URL=mongodb://mongodb:27017
#   networks:
#     pic_network:
#       ipv4_address: 172.18.0.100

volumes:
  paint_mongo_data:
    external: true

networks:
  pic_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
        
# docker compose  --env-file .env.development --env-file ../backend-api/.env.development up -d
